# Generated by Django 4.1.7 on 2024-11-27 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='apellidos',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
    ]
