# Generated by Django 4.1.7 on 2024-12-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_remove_carritoitem_modo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='es_alquiler',
            field=models.BooleanField(default=False),
        ),
    ]
